import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} `}>
        {children}
          <svg className="svg-container" width="0" height="0">
  <defs>
    <filter
    id="electric"
     x="-5%" y="-5%" width="110%" height="110%"
      colorInterpolationFilters="sRGB"
    >
      <feTurbulence
        type="turbulence"
        baseFrequency="0.055"
        numOctaves="5"
        seed="12"
        result="noise"
      >
        <animate
          attributeName="baseFrequency"
          dur="5.5s"
          values="0.012;0.02;0.012"
          repeatCount="indefinite"
        />
      </feTurbulence>

      <feDisplacementMap
        in="SourceGraphic"
        in2="noise"
        scale="15"
        xChannelSelector="R"
        yChannelSelector="G"
      />
    </filter>
  </defs>
</svg>
      </body>
    </html>
  );
}
